### ISSUE TITLE
Glow-tts recipe

### ISSUE THREAD

**Issue by EmreOzkose** [erogol/TTS_recipes#6]
Hello, 

Firstly, thanks for great work. 
Will you share a recipe to train glow-tts on any dataset?

**Comment by erogol** [comment]
we don't have a recipe but you can look at here for glow-tts example configs https://github.com/coqui-ai/TTS/tree/main/TTS/tts/configs

 (Ankara'ya selamlar :smile: )

**Comment by EmreOzkose** [comment]
The point was editing the config file. Thanks for the link, I will check out. 

(Berlin'e bilmukabele :blush:)
